// URLSessionImplementations.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if !os(macOS)
import MobileCoreServices
#endif
#if canImport(UniformTypeIdentifiers)
import UniformTypeIdentifiers
#endif

// Protocol defined for a session data task. This allows mocking out the URLSessionProtocol below since
// you may not want to create or return a real URLSessionDataTask.
public protocol URLSessionDataTaskProtocol {
    func resume()

    var taskIdentifier: Int { get }

    var progress: Progress { get }

    func cancel()
}

// Protocol allowing implementations to alter what is returned or to test their implementations.
public protocol URLSessionProtocol: Sendable {
    // Task which performs the network fetch. Expected to be from URLSession.dataTask(with:completionHandler:) such that a network request
    // is sent off when `.resume()` is called.
    func dataTaskFromProtocol(with request: URLRequest, completionHandler: @escaping @Sendable (Data?, URLResponse?, (any Error)?) -> Void) -> URLSessionDataTaskProtocol
}

extension URLSession: URLSessionProtocol {
  // Passthrough to URLSession.dataTask(with:completionHandler) since URLSessionDataTask conforms to URLSessionDataTaskProtocol and fetches the network data.
  public func dataTaskFromProtocol(with request: URLRequest, completionHandler: @escaping @Sendable (Data?, URLResponse?, (any Error)?) -> Void) -> URLSessionDataTaskProtocol {
    return dataTask(with: request, completionHandler: completionHandler)
  }
}

extension URLSessionDataTask: URLSessionDataTaskProtocol {}

public final class URLSessionRequestBuilderFactory: RequestBuilderFactory, Sendable {
    public init() {}

    public func getNonDecodableBuilder<T>() -> RequestBuilder<T>.Type {
        return URLSessionRequestBuilder<T>.self
    }

    public func getBuilder<T: Decodable>() -> RequestBuilder<T>.Type {
        return URLSessionDecodableRequestBuilder<T>.self
    }
}

fileprivate class URLSessionRequestBuilderConfiguration: @unchecked Sendable {
    private init() {
        let configuration = URLSessionConfiguration.default
        configuration.timeoutIntervalForRequest = 120
        defaultURLSession = URLSession(configuration: configuration, delegate: sessionDelegate, delegateQueue: nil)
    }

    static let shared = URLSessionRequestBuilderConfiguration()
    
    // Store the URLSession's delegate to retain its reference
    let sessionDelegate = SessionDelegate()

    // Store the URLSession to retain its reference
    let defaultURLSession: URLSession

    // Store current URLCredential for every URLSessionTask
    let credentialStore = SynchronizedDictionary<Int, URLCredential>()
}

open class URLSessionRequestBuilder<T: Sendable>: RequestBuilder<T>, @unchecked Sendable {

    required public init(method: String, URLString: String, parameters: [String: any Sendable]?, headers: [String: String] = [:], requiresAuthentication: Bool, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) {
        super.init(method: method, URLString: URLString, parameters: parameters, headers: headers, requiresAuthentication: requiresAuthentication, apiConfiguration: apiConfiguration)
    }

    /**
     May be overridden by a subclass if you want to control the URLSession
     configuration.
     */
    open func createURLSession() -> URLSessionProtocol {
        return URLSessionRequestBuilderConfiguration.shared.defaultURLSession
    }

    /**
     May be overridden by a subclass if you want to control the Content-Type
     that is given to an uploaded form part.

     Return nil to use the default behavior (inferring the Content-Type from
     the file extension).  Return the desired Content-Type otherwise.
     */
    open func contentTypeForFormPart(fileURL: URL) -> String? {
        return nil
    }

    /**
     May be overridden by a subclass if you want to control the URLRequest
     configuration (e.g. to override the cache policy).
     */
    open func createURLRequest(urlSession: URLSessionProtocol, method: HTTPMethod, encoding: ParameterEncoding, headers: [String: String]) throws -> URLRequest {

        guard let url = URL(string: URLString) else {
            throw DownloadException.requestMissingURL
        }

        var originalRequest = URLRequest(url: url)

        originalRequest.httpMethod = method.rawValue

        buildHeaders().forEach { key, value in
            originalRequest.setValue(value, forHTTPHeaderField: key)
        }

        let modifiedRequest = try encoding.encode(request: originalRequest, with: parameters)

        return modifiedRequest
    }

    @discardableResult
    override open func execute(completion: @Sendable @escaping (_ result: Swift.Result<Response<T>, ErrorResponse>) -> Void) -> RequestTask {
        let urlSession = createURLSession()

        guard let xMethod = HTTPMethod(rawValue: method) else {
            fatalError("Unsupported Http method - \(method)")
        }

        let encoding: ParameterEncoding

        switch xMethod {
        case .get, .head:
            encoding = URLEncoding()

        case .options, .post, .put, .patch, .delete, .trace, .connect:
            let contentType = headers["Content-Type"] ?? "application/json"

            if contentType.hasPrefix("application/") && contentType.contains("json") {
                encoding = JSONDataEncoding()
            } else if contentType.hasPrefix("multipart/form-data") {
                encoding = FormDataEncoding(contentTypeForFormPart: contentTypeForFormPart(fileURL:))
            } else if contentType.hasPrefix("application/x-www-form-urlencoded") {
                encoding = FormURLEncoding()
            } else if contentType.hasPrefix("application/octet-stream") || contentType.hasPrefix("image/") {
                encoding = OctetStreamEncoding()
            } else {
                fatalError("Unsupported Media Type - \(contentType)")
            }
        }

        do {
            let request = try createURLRequest(urlSession: urlSession, method: xMethod, encoding: encoding, headers: headers)

            apiConfiguration.interceptor.intercept(urlRequest: request, urlSession: urlSession, requestBuilder: self) { result in

                switch result {
                case .success(let modifiedRequest):
                    let dataTask = urlSession.dataTaskFromProtocol(with: modifiedRequest) { data, response, error in
                        self.cleanupRequest()

                        self.apiConfiguration.interceptor.didReceiveResponse(urlRequest: modifiedRequest, urlSession: urlSession, requestBuilder: self, data: data, response: response, error: error)

                        if let error = error {
                            self.retryRequest(
                                urlRequest: modifiedRequest,
                                urlSession: urlSession,
                                statusCode: -1,
                                data: data,
                                response: response,
                                error: error,
                                completion: completion
                            )
                            return
                        }

                        guard let httpResponse = response as? HTTPURLResponse else {
                            self.retryRequest(
                                urlRequest: modifiedRequest,
                                urlSession: urlSession,
                                statusCode: -2,
                                data: data,
                                response: response,
                                error: DecodableRequestBuilderError.nilHTTPResponse,
                                completion: completion
                            )
                            return
                        }

                        guard self.apiConfiguration.successfulStatusCodeRange.contains(httpResponse.statusCode) else {
                            self.retryRequest(
                                urlRequest: modifiedRequest,
                                urlSession: urlSession,
                                statusCode: httpResponse.statusCode,
                                data: data,
                                response: httpResponse,
                                error: DecodableRequestBuilderError.unsuccessfulHTTPStatusCode,
                                completion: completion
                            )
                            return
                        }

                        self.processRequestResponse(urlRequest: modifiedRequest, urlSession: urlSession, data: data, httpResponse: httpResponse, error: error, completion: completion)
                    }

                    self.onProgressReady?(dataTask.progress)

                    URLSessionRequestBuilderConfiguration.shared.credentialStore[dataTask.taskIdentifier] = self.credential

                    self.requestTask.set(task: dataTask)

                    self.apiConfiguration.interceptor.willSendRequest(urlRequest: modifiedRequest, urlSession: urlSession, requestBuilder: self)

                    dataTask.resume()

                case .failure(let error):
                    self.apiConfiguration.interceptor.didComplete(urlRequest: request, urlSession: urlSession, requestBuilder: self, data: nil, response: nil, result: .failure(error))
                    self.apiConfiguration.apiResponseQueue.async {
                        completion(.failure(ErrorResponse.error(415, nil, nil, error)))
                    }
                }
            }
        } catch {
            // Request creation failed - create a minimal request for error reporting
            let failedURL = URL(string: URLString) ?? URL(string: "about:blank")!
            var failedRequest = URLRequest(url: failedURL)
            failedRequest.httpMethod = method

            self.apiConfiguration.interceptor.didComplete(urlRequest: failedRequest, urlSession: urlSession, requestBuilder: self, data: nil, response: nil, result: .failure(error))

            self.apiConfiguration.apiResponseQueue.async {
                completion(.failure(ErrorResponse.error(415, nil, nil, error)))
            }
        }

        return requestTask
    }

    private func cleanupRequest() {
        if let task = requestTask.get() {
            URLSessionRequestBuilderConfiguration.shared.credentialStore[task.taskIdentifier] = nil
        }
    }

    private func retryRequest(urlRequest: URLRequest, urlSession: URLSessionProtocol, statusCode: Int, data: Data?, response: URLResponse?, error: Error, completion: @Sendable @escaping (_ result: Swift.Result<Response<T>, ErrorResponse>) -> Void) {
        self.apiConfiguration.interceptor.retry(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: data, response: response, error: error) { retry in
            switch retry {
            case .retry:
                self.execute(completion: completion)

            case .dontRetry:
                self.apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: data, response: response, result: .failure(error))
                self.apiConfiguration.apiResponseQueue.async {
                    completion(.failure(ErrorResponse.error(statusCode, data, response, error)))
                }
            }
        }
    }

    fileprivate func processRequestResponse(urlRequest: URLRequest, urlSession: URLSessionProtocol, data: Data?, httpResponse: HTTPURLResponse, error: Error?, completion: @Sendable @escaping (_ result: Swift.Result<Response<T>, ErrorResponse>) -> Void) {

        switch T.self {
        case is Void.Type:
            let result = () as! T
            apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: data, response: httpResponse, result: .success(result))
            completion(.success(Response(response: httpResponse, body: result, bodyData: data)))

        default:
            fatalError("Unsupported Response Body Type - \(String(describing: T.self))")
        }

    }

    open func buildHeaders() -> [String: String] {
        var httpHeaders: [String: String] = [:]
        for (key, value) in apiConfiguration.customHeaders {
            httpHeaders[key] = value
        }
        for (key, value) in headers {
            httpHeaders[key] = value
        }
        return httpHeaders
    }

    fileprivate func getFileName(fromContentDisposition contentDisposition: String?) -> String? {

        guard let contentDisposition = contentDisposition else {
            return nil
        }

        let items = contentDisposition.components(separatedBy: ";")

        var filename: String?

        for contentItem in items {

            let filenameKey = "filename="
            guard let range = contentItem.range(of: filenameKey) else {
                continue
            }

            filename = contentItem
            return filename?
                .replacingCharacters(in: range, with: "")
                .replacingOccurrences(of: "\"", with: "")
                .trimmingCharacters(in: .whitespacesAndNewlines)
        }

        return filename

    }

    fileprivate func getPath(from url: URL) throws -> String {

        guard var path = URLComponents(url: url, resolvingAgainstBaseURL: true)?.path else {
            throw DownloadException.requestMissingPath
        }

        if path.hasPrefix("/") {
            path.remove(at: path.startIndex)
        }

        return path

    }

    fileprivate func getURL(from urlRequest: URLRequest) throws -> URL {

        guard let url = urlRequest.url else {
            throw DownloadException.requestMissingURL
        }

        return url
    }

}

open class URLSessionDecodableRequestBuilder<T: Decodable & Sendable>: URLSessionRequestBuilder<T>, @unchecked Sendable {
    override fileprivate func processRequestResponse(urlRequest: URLRequest, urlSession: URLSessionProtocol, data: Data?, httpResponse: HTTPURLResponse, error: Error?, completion: @Sendable @escaping (_ result: Swift.Result<Response<T>, ErrorResponse>) -> Void) {

        switch T.self {
        case is String.Type:
            let body = data.flatMap { String(data: $0, encoding: .utf8) } ?? ""
            apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: data, response: httpResponse, result: .success(body as! T))
            completion(.success(Response<T>(response: httpResponse, body: body as! T, bodyData: data)))

        case is URL.Type:
            do {
                guard error == nil else {
                    throw DownloadException.responseFailed
                }

                guard let data = data else {
                    throw DownloadException.responseDataMissing
                }

                let fileManager = FileManager.default
                let cachesDirectory = fileManager.urls(for: .cachesDirectory, in: .userDomainMask)[0]
                let requestURL = try getURL(from: urlRequest)

                var requestPath = try getPath(from: requestURL)

                if let headerFileName = getFileName(fromContentDisposition: httpResponse.allHeaderFields["Content-Disposition"] as? String) {
                    requestPath = requestPath.appending("/\(headerFileName)")
                } else {
                    requestPath = requestPath.appending("/tmp.Api.\(UUID().uuidString)")
                }

                let filePath = cachesDirectory.appendingPathComponent(requestPath)
                let directoryPath = filePath.deletingLastPathComponent().path

                try fileManager.createDirectory(atPath: directoryPath, withIntermediateDirectories: true, attributes: nil)
                try data.write(to: filePath, options: .atomic)

                apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: data, response: httpResponse, result: .success(filePath as! T))
                completion(.success(Response(response: httpResponse, body: filePath as! T, bodyData: data)))

            } catch let requestParserError as DownloadException {
                apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: data, response: httpResponse, result: .failure(requestParserError))
                completion(.failure(ErrorResponse.error(400, data, httpResponse, requestParserError)))
            } catch {
                apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: data, response: httpResponse, result: .failure(error))
                completion(.failure(ErrorResponse.error(400, data, httpResponse, error)))
            }

        case is Void.Type:
            let result = () as! T
            apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: data, response: httpResponse, result: .success(result))
            completion(.success(Response(response: httpResponse, body: result, bodyData: data)))

        case is Data.Type:
            let result = data as! T
            apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: data, response: httpResponse, result: .success(result))
            completion(.success(Response(response: httpResponse, body: result, bodyData: data)))

        default:
            guard let unwrappedData = data, !unwrappedData.isEmpty else {
                if let expressibleByNilLiteralType = T.self as? ExpressibleByNilLiteral.Type {
                    let result = expressibleByNilLiteralType.init(nilLiteral: ()) as! T
                    apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: data, response: httpResponse, result: .success(result))
                    completion(.success(Response(response: httpResponse, body: result, bodyData: data)))
                } else {
                    let emptyDataError = DecodableRequestBuilderError.emptyDataResponse
                    apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: nil, response: httpResponse, result: .failure(emptyDataError))
                    completion(.failure(ErrorResponse.error(httpResponse.statusCode, nil, httpResponse, emptyDataError)))
                }
                return
            }

            let decodeResult = apiConfiguration.codableHelper.decode(T.self, from: unwrappedData)

            switch decodeResult {
            case let .success(decodableObj):
                apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: unwrappedData, response: httpResponse, result: .success(decodableObj))
                completion(.success(Response(response: httpResponse, body: decodableObj, bodyData: unwrappedData)))
            case let .failure(error):
                apiConfiguration.interceptor.didComplete(urlRequest: urlRequest, urlSession: urlSession, requestBuilder: self, data: unwrappedData, response: httpResponse, result: .failure(error))
                completion(.failure(ErrorResponse.error(httpResponse.statusCode, unwrappedData, httpResponse, error)))
            }
        }
    }
}

fileprivate final class SessionDelegate: NSObject, URLSessionTaskDelegate {
    func urlSession(_ session: URLSession, task: URLSessionTask, didReceive challenge: URLAuthenticationChallenge, completionHandler: @Sendable @escaping (URLSession.AuthChallengeDisposition, URLCredential?) -> Void) {

        var disposition: URLSession.AuthChallengeDisposition = .performDefaultHandling

        var credential: URLCredential?

        if challenge.previousFailureCount > 0 {
            disposition = .rejectProtectionSpace
        } else {
            credential = URLSessionRequestBuilderConfiguration.shared.credentialStore[task.taskIdentifier] ?? session.configuration.urlCredentialStorage?.defaultCredential(for: challenge.protectionSpace)

            if credential != nil {
                disposition = .useCredential
            }
        }

        completionHandler(disposition, credential)
    }
}

public enum HTTPMethod: String {
    case options = "OPTIONS"
    case get = "GET"
    case head = "HEAD"
    case post = "POST"
    case put = "PUT"
    case patch = "PATCH"
    case delete = "DELETE"
    case trace = "TRACE"
    case connect = "CONNECT"
}

public protocol ParameterEncoding {
    func encode(request: URLRequest, with parameters: [String: any Sendable]?) throws -> URLRequest
}

private class URLEncoding: ParameterEncoding {
    func encode(request: URLRequest, with parameters: [String: any Sendable]?) throws -> URLRequest {

        var urlRequest = request

        guard let parameters = parameters else { return urlRequest }

        guard let url = urlRequest.url else {
            throw DownloadException.requestMissingURL
        }

        if var urlComponents = URLComponents(url: url, resolvingAgainstBaseURL: false), !parameters.isEmpty {
            urlComponents.queryItems = APIHelper.mapValuesToQueryItems(parameters)
            urlRequest.url = urlComponents.url
        }

        return urlRequest
    }
}

private enum MultipartBodyPart {
    /// Inline bytes (boundary text, headers, small text field values).
    case inline(Data)
    /// File on disk — read in chunks during the upload, never loaded into memory.
    case file(URL)
}

/// Subclass of `InputStream` that produces a multipart/form-data body on
/// demand. URLSession calls `read(_:maxLength:)` repeatedly while sending
/// the request; we fill the buffer from the current `parts[partIndex]`,
/// transitioning to the next part when one ends. File parts are streamed
/// from disk in chunks via `FileHandle` — no part's bytes are ever held
/// fully in memory.
private final class MultipartInputStream: InputStream {
    private let parts: [MultipartBodyPart]
    private var partIndex = 0
    private var inlineOffset = 0
    private var fileHandle: FileHandle? = nil
    private var _status: Stream.Status = .notOpen
    private var _error: Error? = nil

    init(parts: [MultipartBodyPart]) {
        self.parts = parts
        super.init(data: Data())
    }

    override func open() { _status = .open }

    override func close() {
        try? fileHandle?.close()
        fileHandle = nil
        _status = .closed
    }

    override var streamStatus: Stream.Status { _status }
    override var streamError: Error? { _error }
    override var hasBytesAvailable: Bool { partIndex < parts.count }

    override func read(_ buffer: UnsafeMutablePointer<UInt8>, maxLength len: Int) -> Int {
        var totalWritten = 0
        while totalWritten < len && partIndex < parts.count {
            let remaining = len - totalWritten
            switch parts[partIndex] {
            case .inline(let data):
                let chunkLen = min(remaining, data.count - inlineOffset)
                if chunkLen > 0 {
                    data.withUnsafeBytes { rawBuf in
                        guard let base = rawBuf.baseAddress else { return }
                        memcpy(buffer + totalWritten, base.advanced(by: inlineOffset), chunkLen)
                    }
                    inlineOffset += chunkLen
                    totalWritten += chunkLen
                }
                if inlineOffset >= data.count { advance() }
            case .file(let url):
                if fileHandle == nil {
                    do {
                        fileHandle = try FileHandle(forReadingFrom: url)
                    } catch {
                        _error = error
                        _status = .error
                        return -1
                    }
                }
                guard let fh = fileHandle else { return -1 }
                let chunk: Data
                if #available(iOS 13.4, macOS 10.15.4, tvOS 13.4, watchOS 6.2, *) {
                    do {
                        chunk = try fh.read(upToCount: remaining) ?? Data()
                    } catch {
                        _error = error
                        _status = .error
                        return -1
                    }
                } else {
                    chunk = fh.readData(ofLength: remaining)
                }
                if chunk.isEmpty {
                    advance()
                    continue
                }
                chunk.withUnsafeBytes { rawBuf in
                    guard let base = rawBuf.baseAddress else { return }
                    memcpy(buffer + totalWritten, base, chunk.count)
                }
                totalWritten += chunk.count
            }
        }
        return totalWritten
    }

    private func advance() {
        if case .file = parts[partIndex] {
            try? fileHandle?.close()
            fileHandle = nil
        }
        partIndex += 1
        inlineOffset = 0
    }

    override func getBuffer(_ buffer: UnsafeMutablePointer<UnsafeMutablePointer<UInt8>?>, length: UnsafeMutablePointer<Int>) -> Bool {
        return false
    }

    override func property(forKey key: Stream.PropertyKey) -> Any? { nil }
    override func setProperty(_ property: Any?, forKey key: Stream.PropertyKey) -> Bool { false }

    private weak var _delegate: StreamDelegate?
    override var delegate: StreamDelegate? {
        get { _delegate }
        set { _delegate = newValue }
    }
    override func schedule(in runLoop: RunLoop, forMode mode: RunLoop.Mode) {}
    override func remove(from runLoop: RunLoop, forMode mode: RunLoop.Mode) {}
}

private class FormDataEncoding: ParameterEncoding {

    let contentTypeForFormPart: (_ fileURL: URL) -> String?

    init(contentTypeForFormPart: @Sendable @escaping (_ fileURL: URL) -> String?) {
        self.contentTypeForFormPart = contentTypeForFormPart
    }

    func encode(request: URLRequest, with parameters: [String: any Sendable]?) throws -> URLRequest {

        var urlRequest = request

        guard var parameters = parameters, !parameters.isEmpty else {
            return urlRequest
        }

        // `__form_file_fields` is injected by the generated API code when the
        // operation has the `x-form-file-fields` vendor extension. Each entry
        // is the leaf baseName (e.g. "audio") — matched against the last
        // bracket segment of each parameter key. Their string values are
        // treated as filenames resolved against the app's Documents dir, and
        // their contents are streamed during the upload (never loaded in RAM).
        let fileFieldNames: Set<String> = (parameters.removeValue(forKey: "__form_file_fields") as? [String]).map(Set.init) ?? []

        let boundary = "Boundary-\(UUID().uuidString)"
        urlRequest.setValue("multipart/form-data; boundary=\(boundary)", forHTTPHeaderField: "Content-Type")

        var parts: [MultipartBodyPart] = []

        for (key, value) in parameters {
            // Leaf segment of the bracket-keyed name.
            // "upsert[data][0][audio]" -> "audio"; "user_id" -> "user_id".
            let leafName: String = {
                guard let bracketStart = key.lastIndex(of: "[") else { return key }
                let after = key.index(after: bracketStart)
                guard let bracketEnd = key[after...].firstIndex(of: "]") else { return key }
                return String(key[after..<bracketEnd])
            }()
            let isFileField = fileFieldNames.contains(leafName)

            for v in (value as? [Any] ?? [value]) {
                if isFileField, let filename = v as? String, !filename.isEmpty {
                    let fileURL = Self.resolveFile(filename)
                    let mime = contentTypeForFormPart(fileURL) ?? mimeType(for: fileURL)
                    // Send only the basename in Content-Disposition — never
                    // leak client-side paths to the server (the server uses
                    // this filename verbatim when writing to disk, and any
                    // leading directory components would either escape `dir`
                    // (absolute paths) or reference nonexistent subdirs).
                    parts.append(.inline(Self.partHeaderForFile(boundary: boundary, isFirst: parts.isEmpty, name: key, filename: fileURL.lastPathComponent, mime: mime)))
                    parts.append(.file(fileURL))
                    continue
                }

                switch v {
                case let fileURL as URL:
                    let mime = contentTypeForFormPart(fileURL) ?? mimeType(for: fileURL)
                    parts.append(.inline(Self.partHeaderForFile(boundary: boundary, isFirst: parts.isEmpty, name: key, filename: fileURL.lastPathComponent, mime: mime)))
                    parts.append(.file(fileURL))
                case let string as String:
                    parts.append(.inline(Self.inlineFieldPart(boundary: boundary, isFirst: parts.isEmpty, name: key, value: Data(string.utf8))))
                case let number as NSNumber:
                    parts.append(.inline(Self.inlineFieldPart(boundary: boundary, isFirst: parts.isEmpty, name: key, value: Data(number.stringValue.utf8))))
                case let data as Data:
                    parts.append(.inline(Self.inlineFieldPart(boundary: boundary, isFirst: parts.isEmpty, name: key, value: data)))
                case let uuid as UUID:
                    parts.append(.inline(Self.inlineFieldPart(boundary: boundary, isFirst: parts.isEmpty, name: key, value: Data(uuid.uuidString.utf8))))
                default:
                    fatalError("Unprocessable value \(v) with key \(key)")
                }
            }
        }

        parts.append(.inline(Data("\r\n--\(boundary)--\r\n".utf8)))

        // Content-Length up-front: sum inline data lengths + on-disk file sizes
        // (via FileManager attributes — no read).
        let contentLength = parts.reduce(Int64(0)) { acc, part in
            switch part {
            case .inline(let data):
                return acc + Int64(data.count)
            case .file(let url):
                let size = (try? FileManager.default.attributesOfItem(atPath: url.path)[.size] as? NSNumber)?.int64Value ?? 0
                return acc + size
            }
        }
        urlRequest.setValue(String(contentLength), forHTTPHeaderField: "Content-Length")

        urlRequest.httpBodyStream = MultipartInputStream(parts: parts)

        return urlRequest
    }

    /// Resolve a filename to an on-disk URL. Absolute paths used as-is;
    /// bare filenames looked up under the app's Documents directory.
    private static func resolveFile(_ filename: String) -> URL {
        if filename.hasPrefix("/") {
            return URL(fileURLWithPath: filename)
        }
        let base = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSTemporaryDirectory())
        return base.appendingPathComponent(filename)
    }

    private static func partHeaderForFile(boundary: String, isFirst: Bool, name: String, filename: String, mime: String) -> Data {
        let lead = isFirst ? "" : "\r\n"
        return Data("\(lead)--\(boundary)\r\nContent-Disposition: form-data; name=\"\(name)\"; filename=\"\(filename)\"\r\nContent-Type: \(mime)\r\n\r\n".utf8)
    }

    private static func inlineFieldPart(boundary: String, isFirst: Bool, name: String, value: Data) -> Data {
        let lead = isFirst ? "" : "\r\n"
        var blob = Data("\(lead)--\(boundary)\r\nContent-Disposition: form-data; name=\"\(name)\"\r\n\r\n".utf8)
        blob.append(value)
        return blob
    }

    func mimeType(for url: URL) -> String {
        let pathExtension = url.pathExtension

        if #available(macOS 11.0, iOS 14.0, tvOS 14.0, watchOS 7.0, *) {
            #if canImport(UniformTypeIdentifiers)
            if let utType = UTType(filenameExtension: pathExtension) {
                return utType.preferredMIMEType ?? "application/octet-stream"
            }
            #else
            return "application/octet-stream" 
            #endif
        } else {
            if let uti = UTTypeCreatePreferredIdentifierForTag(kUTTagClassFilenameExtension, pathExtension as NSString, nil)?.takeRetainedValue(),
                    let mimetype = UTTypeCopyPreferredTagWithClass(uti, kUTTagClassMIMEType)?.takeRetainedValue() {
                return mimetype as String
            }
            return "application/octet-stream"
        }
        return "application/octet-stream"
    }

}

private class FormURLEncoding: ParameterEncoding {
    func encode(request: URLRequest, with parameters: [String: any Sendable]?) throws -> URLRequest {

        var urlRequest = request

        var requestBodyComponents = URLComponents()
        let queryItems = APIHelper.mapValuesToQueryItems(parameters ?? [:])
        
        /// `httpBody` needs to be percent encoded
        /// -> https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST
        /// "application/x-www-form-urlencoded: [...] Non-alphanumeric characters in both keys and values are percent-encoded"
        let percentEncodedQueryItems = queryItems?.compactMap { queryItem in
            return URLQueryItem(
                name: queryItem.name.addingPercentEncoding(withAllowedCharacters: .alphanumerics) ?? queryItem.name,
                value: queryItem.value?.addingPercentEncoding(withAllowedCharacters: .alphanumerics) ?? queryItem.value)
        }
        requestBodyComponents.queryItems = percentEncodedQueryItems

        if urlRequest.value(forHTTPHeaderField: "Content-Type") == nil {
            urlRequest.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")
        }

        /// We can't use `requestBodyComponents.percentEncodedQuery` since this does NOT percent encode the `+` sign
        /// that is why we do the percent encoding manually for each key/value pair
        urlRequest.httpBody = requestBodyComponents.query?.data(using: .utf8)

        return urlRequest
    }
}

private class OctetStreamEncoding: ParameterEncoding {
    func encode(request: URLRequest, with parameters: [String: any Sendable]?) throws -> URLRequest {

        var urlRequest = request

        guard let body = parameters?["body"] else { return urlRequest }

        if urlRequest.value(forHTTPHeaderField: "Content-Type") == nil {
            urlRequest.setValue("application/octet-stream", forHTTPHeaderField: "Content-Type")
        }

        switch body {
        case let fileURL as URL:
            urlRequest.httpBody = try Data(contentsOf: fileURL)
        case let data as Data:
            urlRequest.httpBody = data
        default:
            fatalError("Unprocessable body \(body)")
        }

        return urlRequest
    }
}

private extension Data {
    /// Append string to Data
    ///
    /// Rather than littering my code with calls to `dataUsingEncoding` to convert strings to Data, and then add that data to the Data, this wraps it in a nice convenient little extension to Data. This converts using UTF-8.
    ///
    /// - parameter string:       The string to be added to the `Data`.

    mutating func append(_ string: String) {
        if let data = string.data(using: .utf8) {
            append(data)
        }
    }
}

private extension Optional where Wrapped == Data {
    var orEmpty: Data {
        self ?? Data()
    }
}

extension JSONDataEncoding: ParameterEncoding {}

public enum OpenAPIInterceptorRetry {
    case retry
    case dontRetry
}

public protocol OpenAPIInterceptor: Sendable {
    // MARK: - Request Modification & Retry

    /// Called before the request is sent. Allows modifying the URLRequest (e.g., adding authentication headers).
    func intercept<T>(urlRequest: URLRequest, urlSession: URLSessionProtocol, requestBuilder: RequestBuilder<T>, completion: @Sendable @escaping (Result<URLRequest, Error>) -> Void)

    /// Called when a request fails. Allows the interceptor to decide whether to retry the request.
    func retry<T>(urlRequest: URLRequest, urlSession: URLSessionProtocol, requestBuilder: RequestBuilder<T>, data: Data?, response: URLResponse?, error: Error, completion: @Sendable @escaping (OpenAPIInterceptorRetry) -> Void)

    // MARK: - Lifecycle Hooks

    /// Called right before the request is sent, after all modifications from `intercept()` have been applied.
    /// Useful for logging the final request that will be sent.
    func willSendRequest<T>(urlRequest: URLRequest, urlSession: URLSessionProtocol, requestBuilder: RequestBuilder<T>)

    /// Called when the raw response is received, before any processing or decoding.
    /// Useful for logging raw responses or performing custom validation.
    func didReceiveResponse<T>(urlRequest: URLRequest, urlSession: URLSessionProtocol, requestBuilder: RequestBuilder<T>, data: Data?, response: URLResponse?, error: Error?)

    /// Called after the request completes (either success or failure).
    /// Useful for cleanup, analytics, or performance monitoring.
    func didComplete<T>(urlRequest: URLRequest, urlSession: URLSessionProtocol, requestBuilder: RequestBuilder<T>, data: Data?, response: URLResponse?, result: Result<T, Error>)
}

// MARK: - Default Implementations (No-op)

public extension OpenAPIInterceptor {
    func willSendRequest<T>(urlRequest: URLRequest, urlSession: URLSessionProtocol, requestBuilder: RequestBuilder<T>) {}

    func didReceiveResponse<T>(urlRequest: URLRequest, urlSession: URLSessionProtocol, requestBuilder: RequestBuilder<T>, data: Data?, response: URLResponse?, error: Error?) {}

    func didComplete<T>(urlRequest: URLRequest, urlSession: URLSessionProtocol, requestBuilder: RequestBuilder<T>, data: Data?, response: URLResponse?, result: Result<T, Error>) {}
}

public final class DefaultOpenAPIInterceptor: OpenAPIInterceptor {
    public init() {}

    public func intercept<T>(urlRequest: URLRequest, urlSession: URLSessionProtocol, requestBuilder: RequestBuilder<T>, completion: @Sendable @escaping (Result<URLRequest, any Error>) -> Void) {
        completion(.success(urlRequest))
    }

    public func retry<T>(urlRequest: URLRequest, urlSession: URLSessionProtocol, requestBuilder: RequestBuilder<T>, data: Data?, response: URLResponse?, error: Error, completion: @Sendable @escaping (OpenAPIInterceptorRetry) -> Void) {
        completion(.dontRetry)
    }
}
